language: php
php:
- 5.5
- 5.4
-hvm
  script:bash ./deploy.sh
  script: phpunit Test.php
  env: 
  global:
  -ENCRYPTION_LABEL: "<.... etiqueta de cifrado de la etapa anterior ....>"
  -COMMIT_AUTHOR_EMAIL: "joseisrael.reyes@uptc.edu.co"
