language: node.js
node_js:
- stable
  script:bash ./deploy.sh
  env: 
  global:
  -ENCRYPTION_LABEL: "<.... etiqueta de cifrado de la etapa anterior ....>"
  -COMMIT_AUTHOR_EMAIL: "joseisrael.reyes@uptc.edu.co"
